### ISSUE TITLE
NUT_DATA.sql is missing

### ISSUE THREAD

**Issue by alvinwoon** [skeww/mysql-usdanlsr28#1]
Also, columns for Amount and Num_Data_Pts under WEIGHT table needs to have higher Length. Certain rows fail to import. 

Thanks for doing this!

**Comment by skeww** [comment]
> NUT_DATA.sql  
> I can't believe that I missed that! So sorry, I'll add it now.
> Also adjust the definition of the WEIGHT table.

**Comment by skeww** [comment]
If you have successfully imported the rows with a 4-digit value, it would be truncate to 999.

Here is a fix for the data in that table

```
ALTER TABLE `usdanlsr28`.`WEIGHT` 
CHANGE COLUMN `Num_Data_Pts` `Num_Data_Pts` DECIMAL(4,0) NULL DEFAULT NULL ;
```

```
-- USE usdanlsr28;

UPDATE WEIGHT 
set Num_Data_Pts = 1329
WHERE NDB_NO = '07254' AND Seq = 2;


UPDATE WEIGHT
set Num_Data_Pts = 1587 
WHERE NDB_NO = '07973' AND Seq = 1;


UPDATE WEIGHT 
set Num_Data_Pts = 1627 
WHERE NDB_NO = '07973' AND Seq = 2;
```

If those rows were simply not added here is the insert script for them (Use the same alter script)

```
-- USE usdanlsr28;
 INSERT INTO WEIGHT(    NDB_NO,
    Seq,
    Amount,
    Msre_Desc,
    Gm_Wgt,
    Num_Data_Pts,
    Std_Dev )
 VALUES

 ('07254',2,1,'slice 12 oz pkg',16,1329,NULL),
 ('07973',1,1,'slice',8.1,1587,NULL),
 ('07973',2,1,'raw pr g',15,1627,NULL);
```

I'm sorry that this happened, and I hope that I didn't miss any rows. Here's the regex I used to find them `\('\d+',(.+),(.+),'(.+)',(.+),(\d{0,3}),(.+)\),` in case someone wants to create their own fix-it script

**Comment by skeww** [comment]
Fixed in master.
